"""
Arrhenius-Based Chlorination Kinetics Engine
Consecutive reaction model for phenol chlorination to 2,4-Dichlorophenol

Reaction scheme:
  Phenol + Cl2  → 2-CP + HCl          (k1, desired intermediate)
  2-CP   + Cl2  → 2,4-DCP + HCl       (k2, desired product)
  2,4-DCP + Cl2 → 2,4,6-TCP + HCl     (k3, undesired over-chlorination)

All kinetic parameters from literature for FeCl3-catalyzed aromatic chlorination.
"""

import math


class ChlorinationKinetics:
    """
    Physically accurate CSTR kinetics for phenol chlorination.
    Uses Arrhenius rate law: k = A * exp(-Ea / (R * T))
    """

    # Pre-exponential factors (L / mol / min)
    A1 = 2.4e8   # Phenol → 2-CP
    A2 = 1.1e7   # 2-CP → 2,4-DCP
    A3 = 3.2e6   # 2,4-DCP → 2,4,6-TCP

    # Activation energies (J / mol)
    Ea1 = 62_000
    Ea2 = 68_000
    Ea3 = 74_000

    # Universal gas constant (J / mol / K)
    R = 8.314

    # Heats of reaction (J / mol) — exothermic (negative)
    dH1 = -125_000
    dH2 = -118_000
    dH3 = -110_000

    def rate_constants(self, T_kelvin: float) -> tuple:
        """
        Calculate Arrhenius rate constants at given temperature.

        Args:
            T_kelvin: Temperature in Kelvin

        Returns:
            (k1, k2, k3) in L/mol/min
        """
        if T_kelvin <= 0:
            return 0.0, 0.0, 0.0

        k1 = self.A1 * math.exp(-self.Ea1 / (self.R * T_kelvin))
        k2 = self.A2 * math.exp(-self.Ea2 / (self.R * T_kelvin))
        k3 = self.A3 * math.exp(-self.Ea3 / (self.R * T_kelvin))
        return k1, k2, k3

    def reaction_rates(
        self,
        C_phenol: float,
        C_monochlorophenol: float,
        C_dcp: float,
        C_cl2: float,
        T_celsius: float,
    ) -> tuple:
        """
        Calculate reaction rates for all three consecutive reactions.

        Args:
            C_phenol: Phenol concentration (mol/L)
            C_monochlorophenol: 2-Chlorophenol concentration (mol/L)
            C_dcp: 2,4-Dichlorophenol concentration (mol/L)
            C_cl2: Dissolved chlorine concentration (mol/L)
            T_celsius: Temperature in Celsius

        Returns:
            (r1, r2, r3) reaction rates in mol/L/min
        """
        T_K = T_celsius + 273.15
        k1, k2, k3 = self.rate_constants(T_K)

        r1 = k1 * max(0.0, C_phenol) * max(0.0, C_cl2)
        r2 = k2 * max(0.0, C_monochlorophenol) * max(0.0, C_cl2)
        r3 = k3 * max(0.0, C_dcp) * max(0.0, C_cl2)

        return r1, r2, r3

    def heat_generation_rate(
        self, r1: float, r2: float, r3: float, volume_liters: float
    ) -> float:
        """
        Calculate total heat generated by all reactions.

        Args:
            r1, r2, r3: Reaction rates (mol/L/min)
            volume_liters: Reactor liquid volume (L)

        Returns:
            Heat generation rate in Watts (J/s)
        """
        # Q = -sum(ri * dHi) * V  (negative dH → exothermic → positive Q)
        Q_per_min = -(r1 * self.dH1 + r2 * self.dH2 + r3 * self.dH3) * volume_liters
        Q_watts = Q_per_min / 60.0  # Convert from J/min to J/s (Watts)
        return Q_watts

    def selectivity_2_4_DCP(
        self, C_dcp: float, C_phenol_consumed: float
    ) -> float:
        """
        Calculate selectivity towards desired 2,4-DCP product.

        Selectivity = moles DCP produced / moles phenol consumed

        Args:
            C_dcp: Current 2,4-DCP concentration (mol/L)
            C_phenol_consumed: Total phenol consumed (mol/L)

        Returns:
            Selectivity as fraction (0.0 to 1.0)
        """
        if C_phenol_consumed < 1e-9:
            return 0.0
        return min(1.0, C_dcp / C_phenol_consumed)
